name: Publish GitHub Action
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tgymnich/publish-github-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
